#!/bin/bash
set -x -e
HOST_DIR="${HOST_DIR:-/host}"
RELEASE_FILE="${RELEASE_FILE:-/etc/os-release}"
CONF_FILE="${CONF_FILE:-/run/data/cloud-config}"

mkdir -p $HOST_DIR/run/elemental

function config()
{
    if [ ! -s $CONF_FILE ]; then
        if [ -e ${HOST_DIR}/oem/90_operator.yaml ]; then
            rm -f ${HOST_DIR}/oem/90_operator.yaml
        fi
        return 0
    fi

    if [ ! -e ${HOST_DIR}/oem/90_operator.yaml ] || ! diff $CONF_FILE ${HOST_DIR}/oem/90_operator.yaml >/dev/null; then
        cp -f $CONF_FILE ${HOST_DIR}/oem/90_operator.yaml
    fi
}

function isEqualVersion() {
    if diff $RELEASE_FILE ${HOST_DIR}${RELEASE_FILE} >/dev/null; then
        return 0
    fi
    return 1
}


if ! SYSSTATUS=`nsenter -i -m -t 1 -- systemctl is-system-running`; then
    case "$SYSSTATUS" in
    stopping)
        # Exit if there is a shutdown process already going on
        exit 1
        ;;
    *)
        # other states (degraded, maintenance...) should not stop OS upgrades, see https://github.com/rancher/elemental/issues/901
        ;;
    esac
fi

if isEqualVersion; then
    echo "Upgrade already done with release:"
    cat ${HOST_DIR}${RELEASE_FILE}

    exit 0
fi

config
mount --rbind $HOST_DIR/dev /dev
mount --rbind $HOST_DIR/run /run

if [ "$UPGRADE_RECOVERY_ONLY" = "true" ]; then
    elemental --debug upgrade-recovery --recovery-system.uri dir:/
    exit 0
fi

if [ "$UPGRADE_RECOVERY" = "true" ]; then
    elemental --debug upgrade --recovery --bootloader --system dir:/
else 
    elemental --debug upgrade --bootloader --system dir:/
fi

STATE_PATH=/run/initramfs/elemental-state
[ ! -d "${STATE_PATH}" ] && STATE_PATH=/run/initramfs/cos-state

nsenter -i -m -t 1 -- reboot
exit 1
