name: Integration Tests
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_TESTS: "true"
      ELMNTL_FIRMWARE: "/usr/share/OVMF/OVMF_CODE_4M.fd"
      VERBOSE: "true"
      IMG_REPO: "registry.opensuse.org/devel/unifiedcore/tumbleweed/prs/suse/elemental/pr-${{ github.event.pull_request.number }}/containers"
      OBS_PROJ: "devel:UnifiedCore:Tumbleweed:PRs:SUSE:elemental:PR-${{ github.event.pull_request.number }}"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod
      - name: QEMU/Libvirt installation and configuration
        run: |
          # Install QEMU/Libvirt packages
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager

          # Configure udev
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Wait for OBS project artefacts build and publish
        uses: ./.github/actions/obs/wait-build-and-publish
        with:
          obs_project: ${{ env.OBS_PROJ }}
      - name: Wait for available images to be synced with latest OBS artefact state
        uses: ./.github/actions/obs/wait-image-sync
        with:
          obs_project: ${{ env.OBS_PROJ }}
          image_repo: ${{ env.IMG_REPO }}
      - name: Generate OS disk image
        run: |
          make build-disk
      - name: Run installer test
        run: |
          make test-installer
      - name: Clean installer test
        if: ${{ always() }}
        run: |
          make clean-test || true
      - name: Run customize ISO test
        run: |
          make test-customize-iso
      - name: Clean customize ISO test
        if: ${{ always() }}
        run: |
          make clean-test || true
      - name: Run customize RAW test
        run: |
          make test-customize-raw
      - name: Clean customize RAW test
        if: ${{ always() }}
        run: |
          make clean-test || true
