name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          cache-dependency-path: go.sum
          go-version-file: go.mod
          cache: false
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rootlesskit
      - name: Run tests
        env:
          COV_THRESHOLD: "70"
        run: |
          # Execute the Unit tests
          make VERBOSE=true ROOTLESSKIT=yes unit-tests

          # Remove mock files from coverage analysis
          sed -n -i '/\/mock\//!p' coverprofile.out
          coverage=$(go tool cover -func=coverprofile.out | grep total | grep -Eo "[0-9]+\.[0-9]+")

          if (( $(echo "${coverage} ${COV_THRESHOLD}" | awk '{print ($1 > $2)}') )); then
            echo "Total Coverage is: ${coverage}%"
          else
            echo "Current test coverage (${coverage}%) is below the threshold (${COV_THRESHOLD}%)."
            echo "Failed"
            exit 1
          fi
